//go:build !ignore_autogenerated

/*
Copyright 2025 Edenlab.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnnotationBumpOptions) DeepCopyInto(out *AnnotationBumpOptions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnnotationBumpOptions.
func (in *AnnotationBumpOptions) DeepCopy() *AnnotationBumpOptions {
	if in == nil {
		return nil
	}
	out := new(AnnotationBumpOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LinkerdTrustRotation) DeepCopyInto(out *LinkerdTrustRotation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LinkerdTrustRotation.
func (in *LinkerdTrustRotation) DeepCopy() *LinkerdTrustRotation {
	if in == nil {
		return nil
	}
	out := new(LinkerdTrustRotation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LinkerdTrustRotation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LinkerdTrustRotationList) DeepCopyInto(out *LinkerdTrustRotationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LinkerdTrustRotation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LinkerdTrustRotationList.
func (in *LinkerdTrustRotationList) DeepCopy() *LinkerdTrustRotationList {
	if in == nil {
		return nil
	}
	out := new(LinkerdTrustRotationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LinkerdTrustRotationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LinkerdTrustRotationSpec) DeepCopyInto(out *LinkerdTrustRotationSpec) {
	*out = *in
	out.Trigger = in.Trigger
	in.Rollout.DeepCopyInto(&out.Rollout)
	in.Safety.DeepCopyInto(&out.Safety)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LinkerdTrustRotationSpec.
func (in *LinkerdTrustRotationSpec) DeepCopy() *LinkerdTrustRotationSpec {
	if in == nil {
		return nil
	}
	out := new(LinkerdTrustRotationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LinkerdTrustRotationStatus) DeepCopyInto(out *LinkerdTrustRotationStatus) {
	*out = *in
	if in.Phase != nil {
		in, out := &in.Phase, &out.Phase
		*out = new(Phase)
		**out = **in
	}
	if in.Reason != nil {
		in, out := &in.Reason, &out.Reason
		*out = new(Reason)
		**out = **in
	}
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(string)
		**out = **in
	}
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.LastUpdated != nil {
		in, out := &in.LastUpdated, &out.LastUpdated
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.Progress != nil {
		in, out := &in.Progress, &out.Progress
		*out = new(ProgressStatus)
		**out = **in
	}
	if in.Trust != nil {
		in, out := &in.Trust, &out.Trust
		*out = new(TrustStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Retries != nil {
		in, out := &in.Retries, &out.Retries
		*out = new(RetryStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Cursor != nil {
		in, out := &in.Cursor, &out.Cursor
		*out = new(RolloutCursor)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LinkerdTrustRotationStatus.
func (in *LinkerdTrustRotationStatus) DeepCopy() *LinkerdTrustRotationStatus {
	if in == nil {
		return nil
	}
	out := new(LinkerdTrustRotationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProgressStatus) DeepCopyInto(out *ProgressStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProgressStatus.
func (in *ProgressStatus) DeepCopy() *ProgressStatus {
	if in == nil {
		return nil
	}
	out := new(ProgressStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetryStatus) DeepCopyInto(out *RetryStatus) {
	*out = *in
	if in.LastFailed != nil {
		in, out := &in.LastFailed, &out.LastFailed
		*out = new(WorkRef)
		**out = **in
	}
	if in.LastErrorTime != nil {
		in, out := &in.LastErrorTime, &out.LastErrorTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetryStatus.
func (in *RetryStatus) DeepCopy() *RetryStatus {
	if in == nil {
		return nil
	}
	out := new(RetryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RolloutCursor) DeepCopyInto(out *RolloutCursor) {
	*out = *in
	if in.LastDone != nil {
		in, out := &in.LastDone, &out.LastDone
		*out = new(WorkRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RolloutCursor.
func (in *RolloutCursor) DeepCopy() *RolloutCursor {
	if in == nil {
		return nil
	}
	out := new(RolloutCursor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RolloutSpec) DeepCopyInto(out *RolloutSpec) {
	*out = *in
	in.TargetAnnotationSelector.DeepCopyInto(&out.TargetAnnotationSelector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RolloutSpec.
func (in *RolloutSpec) DeepCopy() *RolloutSpec {
	if in == nil {
		return nil
	}
	out := new(RolloutSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RotationTrigger) DeepCopyInto(out *RotationTrigger) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RotationTrigger.
func (in *RotationTrigger) DeepCopy() *RotationTrigger {
	if in == nil {
		return nil
	}
	out := new(RotationTrigger)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SafetySpec) DeepCopyInto(out *SafetySpec) {
	*out = *in
	if in.PreRolloutDelay != nil {
		in, out := &in.PreRolloutDelay, &out.PreRolloutDelay
		*out = new(v1.Duration)
		**out = **in
	}
	if in.HoldAfterCleanup != nil {
		in, out := &in.HoldAfterCleanup, &out.HoldAfterCleanup
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SafetySpec.
func (in *SafetySpec) DeepCopy() *SafetySpec {
	if in == nil {
		return nil
	}
	out := new(SafetySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetAnnotationSelector) DeepCopyInto(out *TargetAnnotationSelector) {
	*out = *in
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]TargetScope, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetAnnotationSelector.
func (in *TargetAnnotationSelector) DeepCopy() *TargetAnnotationSelector {
	if in == nil {
		return nil
	}
	out := new(TargetAnnotationSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetScope) DeepCopyInto(out *TargetScope) {
	*out = *in
	if in.AllowedNamespaces != nil {
		in, out := &in.AllowedNamespaces, &out.AllowedNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AnnotationBump != nil {
		in, out := &in.AnnotationBump, &out.AnnotationBump
		*out = new(AnnotationBumpOptions)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetScope.
func (in *TargetScope) DeepCopy() *TargetScope {
	if in == nil {
		return nil
	}
	out := new(TargetScope)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrustStatus) DeepCopyInto(out *TrustStatus) {
	*out = *in
	if in.BundleState != nil {
		in, out := &in.BundleState, &out.BundleState
		*out = new(BundleState)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrustStatus.
func (in *TrustStatus) DeepCopy() *TrustStatus {
	if in == nil {
		return nil
	}
	out := new(TrustStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkRef) DeepCopyInto(out *WorkRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkRef.
func (in *WorkRef) DeepCopy() *WorkRef {
	if in == nil {
		return nil
	}
	out := new(WorkRef)
	in.DeepCopyInto(out)
	return out
}
